### ISSUE TITLE
How to run this project? I run "gulp" on the command but not work

### ISSUE THREAD

**Issue by gclsoft** [mining/frontend#6]
```
root@g-virtual-machine:/home/g/work/frontend# gulp
module.js:557
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/g/work/frontend/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by gclsoft** [comment]
```
root@g-virtual-machine:/home/g/work/frontend# node assets/app/scripts/app.js 
/home/g/work/frontend/assets/app/scripts/app.js:3
var miningApp = angular.module('miningApp', [
                ^

ReferenceError: angular is not defined
    at Object.<anonymous> (/home/g/work/frontend/assets/app/scripts/app.js:3:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

**Comment by avelino** [comment]
Project is stopped (unfortunately), we need people to contribute, you have interest?

**Comment by gclsoft** [comment]
YES @avelino
